[hog0, visualization0] = extractHOGFeatures(i03,'CellSize',[44 44],...
                                                'BlockSize',[2 2],...
                                                'BlockOverlap',[1 1],...
                                                'NumBins',18,...
                                                'UseSignedOrientation',true);
figure(1);
subplot(2,2,1);
imshow(i03);
subplot(2,2,2);
plot(visualization0);

[hog2, visualization2] = extractHOGFeatures(i23,'CellSize',[44 44],...
                                                'BlockSize',[2 2],...
                                                'BlockOverlap',[1 1],...
                                                'NumBins',18,...
                                                'UseSignedOrientation',true);
% figure(2);
subplot(2,2,3);
imshow(i23);
subplot(2,2,4);
plot(visualization2);

dis = pdist([hog0; hog2], 'cosine');
