function [ features ] = hierHog(im)
%   Summary of this function goes here
%   Detailed explanation goes here

im3 = impyramid(im, 'reduce');
im2 = impyramid(im3, 'reduce');
im1 = impyramid(im2, 'reduce');

[y1,x1] = size(im1);
features_level11 = extractHOGFeatures(im1,'CellSize',[y1 floor(x1/2)],...
                                                'BlockSize',[1 2],...
                                                'BlockOverlap',[0 0],...
                                                'NumBins',18,...
                                                'UseSignedOrientation',true);
features_level12 = extractHOGFeatures(im1,'CellSize',[floor(y1/2) x1],...
                                                'BlockSize',[2 1],...
                                                'BlockOverlap',[0 0],...
                                                'NumBins',18,...
                                                'UseSignedOrientation',true);
                                            
[y2,x2] = size(im2);
features_level2 = extractHOGFeatures(im2,'CellSize',[floor(y2/2) floor(x2/2)],...
                                                'BlockSize',[2 2],...
                                                'BlockOverlap',[0 0],...
                                                'NumBins',18,...
                                                'UseSignedOrientation',true);

[y3,x3] = size(im3);
features_level3 = extractHOGFeatures(im3,'CellSize',[floor(y3/4) floor(x3/4)],...
                                                'BlockSize',[2 2],...
                                                'BlockOverlap',[0 0],...
                                                'NumBins',18,...
                                                'UseSignedOrientation',true);
[y4,x4] = size(im);
features_level4 = extractHOGFeatures(im,'CellSize',[floor(y4/8) floor(x4/8)],...
                                                'BlockSize',[2 2],...
                                                'BlockOverlap',[0 0],...
                                                'NumBins',18,...
                                                'UseSignedOrientation',true);
% features = zeros(1,1584);
features = 100*[features_level11,features_level12,features_level2,features_level3,features_level4];
end

